#!/usr/bin/env sh

VERSION="0.0.1"
GIT_ROOT_DIR="`git rev-parse --show-toplevel`"

show_version() {
  say "git-wipit v$VERSION"
}

say() {
  printf '%s\n' "$1"
}

branch_name() {
  basename "$(git symbolic-ref HEAD)"
}

wipit() {
  cd $GIT_ROOT_DIR
  git add -A

  if [ "$1" = "-b" ] || [ "$1" = "--branch" ]; then
    say "Going on a branch, good choice."
    if [ -z "$2" ]; then
      git checkout -b "wip/$(branch_name)"
    else
      git checkout -b "$2"
    fi
  fi

  git commit -m "WIP it good!"
  say "WIP IT REAL GOOD!"
}

show_help() {
  cat <<- EOF

usage:
  git wipit [options] [COMMAND] [args]

commands:
  git wipit                       Creates a fast WIP Commit

options:
  -b, --branch                    Create a wip branch instead of a wip commit
  -h, --help                      Display this help information
  -v, --version                   Display this version of git-wipit

EOF
}

case $1 in
	-h|--help) show_help; exit 0 ;;
	-v|--version) show_version; exit 0 ;;
esac

wipit "$@"
